import globals from 'globals';
import wordpress from '@wordpress/eslint-plugin';

export default [
    {
        ignores: [
            'dist/',
            'node_modules/',
            // Vendored third-party libraries are not linted as project source.
            'src/assets/**/vendor/**',
            '**/*.min.js',
            // Auto-generated by scripts/smil-to-waapi.js (dev-only artifact, never
            // shipped to dist); regenerated on build, so not linted as source.
            'src/assets/frontend/src/loading-icons-waapi.js',
            // Type declarations are checked by tsc, not linted.
            '**/*.d.ts',
        ],
    },
    ...wordpress.configs.recommended,
    {
        languageOptions: {
            ecmaVersion: 2021,
            sourceType: 'module',
            parserOptions: {
                ecmaFeatures: {
                    jsx: true,
                },
            },
            globals: {
                ...globals.browser,
                ...globals.es2021,
                ...globals.node,
                wp: 'readonly',
                jQuery: 'readonly',
                ajaxurl: 'readonly',
                fotogridsAjax: 'readonly',
                fotogridsAdminHeader: 'readonly',
                // The non-bundled admin/plain scripts use the React global that
                // WordPress enqueues, rather than importing it.
                React: 'readonly',
            },
        },
        settings: {
            react: {
                version: 'detect',
            },
        },
        rules: {
            // WordPress specific rules. console.warn / console.error are the
            // project's sanctioned diagnostic channels (error paths, catch
            // blocks); only console.log-style debug output is flagged.
            'no-console': ['warn', { allow: ['warn', 'error'] }],
            'no-debugger': 'error',

            // An underscore prefix marks a binding as deliberately unused
            // (e.g. `_linked`, skipped destructure slots).
            'no-unused-vars': [
                'warn',
                {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                    caughtErrors: 'none',
                },
            ],

            // Empty blocks are warned, but an empty catch is a sanctioned idiom
            // here (e.g. best-effort sessionStorage writes that may throw in
            // private mode) so it is not flagged.
            'no-empty': ['warn', { allowEmptyCatch: true }],

            // The automatic JSX runtime makes React-in-scope unnecessary; prop
            // types are carried by TypeScript.
            'react/react-in-jsx-scope': 'off',
            'react/jsx-uses-react': 'off',
            'react/prop-types': 'off',
            'react-hooks/rules-of-hooks': 'error',
            'react-hooks/exhaustive-deps': 'warn',

            // JSDoc is not required on admin JS/JSX (TypeScript carries type info);
            // the WordPress preset's strict JSDoc rules are disabled here.
            'jsdoc/require-param': 'off',
            'jsdoc/require-param-description': 'off',
            'jsdoc/require-returns': 'off',
            'jsdoc/require-returns-description': 'off',
            'jsdoc/check-tag-names': 'off',
            'jsdoc/check-line-alignment': 'off',
            'jsdoc/check-types': 'off',
            'jsdoc/no-undefined-types': 'off',

            // WordPress micro-optimization rule, not a correctness concern.
            '@wordpress/no-unused-vars-before-return': 'off',

            // no-shadow produces large numbers of false positives with reused
            // callback parameter names; disabled in favour of real correctness
            // rules below.
            'no-shadow': 'off',

            // Intentional stylistic patterns in this codebase; not treated as
            // errors. camelcase is off because REST payload keys are snake_case.
            camelcase: 'off',
            'no-bitwise': 'off',
            'no-nested-ternary': 'off',

            // Often a false positive on optional-chaining call expressions; kept
            // visible as a warning rather than a blocking error.
            'no-unused-expressions': 'warn',

            // Real correctness rules kept at error level. The null exception
            // permits the deliberate `== null` (null-or-undefined) idiom.
            'no-undef': 'error',
            eqeqeq: ['error', 'always', { null: 'ignore' }],

            // Settings labels are translated at runtime via __(), which the static
            // .pot extractor cannot see; surfaced as warnings pending a literal
            // string-registration pass rather than blocking the build.
            '@wordpress/i18n-no-variables': 'warn',
            '@wordpress/i18n-translator-comments': 'warn',

            // Formatting is owned entirely by Prettier (prettier/prettier via the
            // WordPress preset); ESLint stylistic rules are intentionally not set
            // here so the two never conflict.
        },
    },
    {
        files: ['**/*.ts', '**/*.tsx'],
        rules: {
            // TypeScript-aware counterpart of no-unused-vars, with the same
            // underscore-prefix convention.
            'no-unused-vars': 'off',
            '@typescript-eslint/no-unused-vars': [
                'warn',
                {
                    argsIgnorePattern: '^_',
                    varsIgnorePattern: '^_',
                    caughtErrors: 'none',
                },
            ],
            // TypeScript resolves identifiers itself, including ambient
            // namespaces such as JSX that no-undef cannot see.
            'no-undef': 'off',
            '@typescript-eslint/no-shadow': 'off',
            '@typescript-eslint/explicit-function-return-type': 'off',
            '@typescript-eslint/explicit-module-boundary-types': 'off',
            '@typescript-eslint/no-explicit-any': 'warn',
        },
    },
];
