<?php
/**
 * Generate the FotoGrids hook reference documentation.
 *
 * Walks the Hooks directory (`Plugin/src/includes/hooks/` and the matching
 * Pro directory), loads every `class-*.php` constant bag it finds, and
 * extracts each constant's name, value, and PHPDoc block via reflection.
 * Emits a Markdown reference suitable for both internal docs and the public
 * developer site.
 *
 * Usage:
 *   php scripts/generate-hooks-doc.php
 *
 * Output:
 *   Plugin/docs/hooks-reference.md
 *
 * @package FotoGrids
 * @since   1.0.0
 */

declare(strict_types=1);

// ---------------------------------------------------------------------------
// Bootstrap. We deliberately do NOT load WordPress - we only need the Hooks
// class files which are self-contained constant bags.
// ---------------------------------------------------------------------------

if ( ! defined( 'ABSPATH' ) ) {
    define( 'ABSPATH', __DIR__ );
}
if ( ! defined( 'WPINC' ) ) {
    define( 'WPINC', 'wp-includes' );
}

$plugin_root = dirname( __DIR__ );
$repo_root   = dirname( $plugin_root );

$free_hooks_dir = $plugin_root . '/src/includes/hooks';
$pro_hooks_dir  = $repo_root . '/Pro/src/includes/hooks';

/**
 * Require every class-*.php file under a Hooks root directory.
 *
 * Expects the layout: {root}/actions/class-*.php, {root}/filters/class-*.php,
 * {root}/js-events/class-*.php. Pro mirrors the same layout but may have
 * only some of the subfolders.
 *
 * @param string $dir Absolute Hooks-root directory path.
 * @return string[] Absolute paths that were loaded.
 */
function hooks_doc_load_dir( string $dir ): array {
    if ( ! is_dir( $dir ) ) {
        return [];
    }
    $loaded = [];
    foreach ( [ 'actions', 'filters', 'js-events' ] as $group ) {
        foreach ( glob( $dir . '/' . $group . '/class-*.php' ) ?: [] as $file ) {
            require_once $file;
            $loaded[] = $file;
        }
    }
    sort( $loaded );
    return $loaded;
}

$free_files = hooks_doc_load_dir( $free_hooks_dir );
$pro_files  = hooks_doc_load_dir( $pro_hooks_dir );

// ---------------------------------------------------------------------------
// Classify each loaded class by namespace + family (action / filter / event).
// Group families into Markdown sections.
// ---------------------------------------------------------------------------

/**
 * Maps a class short-name prefix to a family for grouping in the output.
 *
 * @param string $short_name Class basename (no namespace).
 * @return string One of 'action' | 'filter' | 'js-event' | 'other'.
 */
function hooks_doc_family( string $short_name ): string {
    if ( str_starts_with( $short_name, 'Actions' ) )  return 'action';
    if ( str_starts_with( $short_name, 'Filters' ) )  return 'filter';
    if ( str_starts_with( $short_name, 'JsEvents' ) ) return 'js-event';
    return 'other';
}

$groups = []; // heading => [ [class, kind, plugin], ... ]
foreach ( get_declared_classes() as $fqcn ) {
    if ( ! str_starts_with( $fqcn, 'FotoGrids\\Hooks\\' ) && ! str_starts_with( $fqcn, 'FotoGrids_Pro\\Hooks\\' ) ) {
        continue;
    }
    $short  = substr( $fqcn, strrpos( $fqcn, '\\' ) + 1 );
    $family = hooks_doc_family( $short );
    if ( $family === 'other' ) {
        continue;
    }
    $is_pro = str_starts_with( $fqcn, 'FotoGrids_Pro\\' );
    $heading = sprintf(
        '%s - %s',
        $is_pro ? 'Pro' : 'Free',
        match ( $family ) {
            'action'   => 'Actions',
            'filter'   => 'Filters',
            'js-event' => 'JavaScript Events',
        }
    );
    $groups[ $heading ][] = [
        'class'  => $fqcn,
        'kind'   => $family,
        'plugin' => $is_pro ? 'pro' : 'free',
    ];
}

// Stable ordering: Free first, then Pro; within each, Actions → Filters → JS.
$heading_order = [
    'Free - Actions', 'Free - Filters', 'Free - JavaScript Events',
    'Pro - Actions',  'Pro - Filters',  'Pro - JavaScript Events',
];
uksort(
    $groups,
    static fn( string $a, string $b ): int =>
        array_search( $a, $heading_order, true ) <=> array_search( $b, $heading_order, true )
);

// Within each heading, sort category classes alphabetically.
foreach ( $groups as $heading => $list ) {
    usort( $list, static fn( array $a, array $b ): int => strcmp( $a['class'], $b['class'] ) );
    $groups[ $heading ] = $list;
}

// ---------------------------------------------------------------------------
// Output assembly.
// ---------------------------------------------------------------------------

$lines = [];
$lines[] = '# FotoGrids Hook Reference';
$lines[] = '';
$lines[] = sprintf(
    '<!-- Generated by `scripts/generate-hooks-doc.php` on %s. Do not edit by hand. -->',
    gmdate( 'Y-m-d' )
);
$lines[] = '';
$lines[] = 'Every action, filter, and JavaScript CustomEvent that FotoGrids dispatches';
$lines[] = 'is declared as a constant on one of the small category classes under';
$lines[] = '`FotoGrids\\Hooks\\` (or `FotoGrids_Pro\\Hooks\\`). This page is generated';
$lines[] = 'directly from those classes so it can never drift from the code.';
$lines[] = '';
$lines[] = '* **Actions** - fired with `do_action( Actions_<Category>::CONSTANT, ... )`.';
$lines[] = '* **Filters** - invoked with `apply_filters( Filters_<Category>::CONSTANT, $value, ... )`.';
$lines[] = '* **JavaScript Events** - dispatched on `document` (or the gallery element) via `CustomEvent`. Listen with `addEventListener`.';
$lines[] = '';

// Table of contents.
$lines[] = '## Table of contents';
$lines[] = '';
foreach ( $groups as $heading => $list ) {
    $lines[] = sprintf( '* [%s](#%s)', $heading, hooks_doc_slugify( $heading ) );
    foreach ( $list as $row ) {
        $short = substr( $row['class'], strrpos( $row['class'], '\\' ) + 1 );
        $lines[] = sprintf( '  * [`%s`](#%s)', $short, hooks_doc_slugify( $short ) );
    }
}
$lines[] = '';

$total_constants = 0;
$class_count     = 0;

foreach ( $groups as $heading => $list ) {
    $lines[] = sprintf( '## %s', $heading );
    $lines[] = '';

    foreach ( $list as $row ) {
        $class_count++;
        $short = substr( $row['class'], strrpos( $row['class'], '\\' ) + 1 );
        $rows  = hooks_doc_extract_constants( $row['class'] );

        $lines[] = sprintf( '### `%s`', $short );
        $lines[] = '';
        $lines[] = sprintf( '_FQCN: `%s` - %d hooks._', $row['class'], count( $rows ) );
        $lines[] = '';

        if ( $rows === [] ) {
            $lines[] = '_(none yet - placeholder class for forward-compatibility.)_';
            $lines[] = '';
            continue;
        }

        foreach ( $rows as $constant ) {
            $total_constants++;
            $lines[] = sprintf( '#### `%s`', $constant['value'] );
            $lines[] = '';
            $lines[] = sprintf( '**Constant:** `%s::%s`  ', $row['class'], $constant['name'] );
            $lines[] = sprintf( '**Kind:** %s', hooks_doc_kind_label( $row['kind'] ) );

            if ( $constant['since'] !== '' ) {
                $lines[] = '  ';
                $lines[] = sprintf( '**Since:** %s', $constant['since'] );
            }
            if ( $constant['deprecated'] !== '' ) {
                $lines[] = '  ';
                $lines[] = sprintf( '**Deprecated:** %s', $constant['deprecated'] );
            }

            $lines[] = '';
            if ( $constant['summary'] !== '' ) {
                $lines[] = $constant['summary'];
                $lines[] = '';
            }

            if ( ! empty( $constant['params'] ) ) {
                $lines[] = '| Parameter | Type | Description |';
                $lines[] = '| --- | --- | --- |';
                foreach ( $constant['params'] as $param ) {
                    $lines[] = sprintf(
                        '| `%s` | `%s` | %s |',
                        $param['name'],
                        $param['type'],
                        str_replace( '|', '\\|', $param['description'] )
                    );
                }
                $lines[] = '';
            }

            if ( $constant['event_detail'] !== '' ) {
                $lines[] = sprintf( '**Event detail:** `%s`', $constant['event_detail'] );
                $lines[] = '';
            }
        }
    }
}

$lines[] = '---';
$lines[] = '';
$lines[] = sprintf(
    '_%d hooks documented across %d category classes._',
    $total_constants,
    $class_count
);
$lines[] = '';

$output_dir = $plugin_root . '/docs';
if ( ! is_dir( $output_dir ) ) {
    mkdir( $output_dir, 0755, true );
}
$output_path = $output_dir . '/hooks-reference.md';
file_put_contents( $output_path, implode( PHP_EOL, $lines ) );

printf(
    "Wrote %s (%d hooks across %d classes; %d Free files + %d Pro files loaded)." . PHP_EOL,
    str_replace( $repo_root . '/', '', $output_path ),
    $total_constants,
    $class_count,
    count( $free_files ),
    count( $pro_files )
);

// ---------------------------------------------------------------------------
// Helpers.
// ---------------------------------------------------------------------------

/**
 * Extract constant rows from a Hooks class via reflection.
 *
 * @param class-string $class_name Fully-qualified class name.
 * @return array<int, array{name:string,value:string,summary:string,since:string,
 *                          deprecated:string,event_detail:string,
 *                          params:array<int,array{name:string,type:string,description:string}>}>
 */
function hooks_doc_extract_constants( string $class_name ): array {
    $reflection = new ReflectionClass( $class_name );
    $rows = [];

    foreach ( $reflection->getReflectionConstants() as $constant ) {
        $doc = $constant->getDocComment();
        $parsed = hooks_doc_parse_docblock( $doc === false ? '' : $doc );

        $rows[] = [
            'name'         => $constant->getName(),
            'value'        => (string) $constant->getValue(),
            'summary'      => $parsed['summary'],
            'since'        => $parsed['since'],
            'deprecated'   => $parsed['deprecated'],
            'event_detail' => $parsed['event_detail'],
            'params'       => $parsed['params'],
        ];
    }

    usort(
        $rows,
        static fn( array $a, array $b ): int => strcmp( $a['value'], $b['value'] )
    );

    return $rows;
}

/**
 * Parse a PHPDoc comment block into a structured array.
 *
 * @param string $doc Raw PHPDoc comment (may be empty).
 * @return array{summary:string,since:string,deprecated:string,event_detail:string,
 *               params:array<int,array{name:string,type:string,description:string}>}
 */
function hooks_doc_parse_docblock( string $doc ): array {
    $summary_lines = [];
    $since         = '';
    $deprecated    = '';
    $event_detail  = '';
    $params        = [];

    if ( $doc === '' ) {
        return [
            'summary'      => '',
            'since'        => '',
            'deprecated'   => '',
            'event_detail' => '',
            'params'       => $params,
        ];
    }

    $doc = preg_replace( '#^\s*/\*\*|\*/\s*$#m', '', $doc ) ?? $doc;
    $raw_lines = preg_split( '/\R/u', $doc ) ?: [];

    foreach ( $raw_lines as $raw_line ) {
        $line = preg_replace( '/^\s*\*\s?/', '', $raw_line ) ?? $raw_line;
        $trim = trim( $line );

        if ( $trim === '' ) {
            if ( $summary_lines !== [] ) {
                $summary_lines[] = '';
            }
            continue;
        }

        if ( strncmp( $trim, '@since', 6 ) === 0 ) {
            $since = trim( substr( $trim, 6 ) );
            continue;
        }
        if ( strncmp( $trim, '@deprecated', 11 ) === 0 ) {
            $deprecated = trim( substr( $trim, 11 ) );
            continue;
        }
        if ( strncmp( $trim, '@event-detail', 13 ) === 0 ) {
            $event_detail = trim( substr( $trim, 13 ) );
            continue;
        }
        if ( strncmp( $trim, '@param', 6 ) === 0 ) {
            $params[] = hooks_doc_parse_param( substr( $trim, 6 ) );
            continue;
        }

        $summary_lines[] = $trim;
    }

    return [
        'summary'      => trim( implode( "\n", $summary_lines ) ),
        'since'        => $since,
        'deprecated'   => $deprecated,
        'event_detail' => $event_detail,
        'params'       => $params,
    ];
}

/**
 * Parse a single @param line into name/type/description.
 *
 * @param string $body Everything after "@param" (no leading "@param").
 * @return array{name:string,type:string,description:string}
 */
function hooks_doc_parse_param( string $body ): array {
    $body = trim( $body );

    if ( preg_match( '/^(\S+)\s+(\$[A-Za-z_][A-Za-z0-9_]*)(?:\s+(.*))?$/u', $body, $matches ) === 1 ) {
        return [
            'type'        => $matches[1],
            'name'        => $matches[2],
            'description' => isset( $matches[3] ) ? trim( $matches[3] ) : '',
        ];
    }

    return [
        'type'        => 'mixed',
        'name'        => '',
        'description' => $body,
    ];
}

/**
 * Build a slug suitable for a GitHub-flavoured Markdown anchor.
 */
function hooks_doc_slugify( string $heading ): string {
    $slug = strtolower( $heading );
    $slug = preg_replace( '/[^a-z0-9\s-]/u', '', $slug ) ?? $slug;
    $slug = preg_replace( '/\s+/u', '-', trim( $slug ) ) ?? $slug;
    return $slug;
}

/**
 * Human-readable label for a hook kind.
 */
function hooks_doc_kind_label( string $kind ): string {
    return match ( $kind ) {
        'action'   => 'Action (`do_action`)',
        'filter'   => 'Filter (`apply_filters`)',
        'js-event' => 'JavaScript CustomEvent',
        default    => $kind,
    };
}
