<?php
/**
 * Regenerates includes/catalog/catalog-strings.php from the settings catalog.
 *
 * @package FotoGrids\Scripts
 * @since   1.1.1
 */

declare(strict_types=1);

if ( 'cli' !== PHP_SAPI ) {
	exit( 1 );
}

/**
 * Catalog keys whose values are rendered to the user.
 */
const CATALOG_TEXT_KEYS = array(
	'description',
	'help',
	'label',
	'message',
	'note',
	'placeholder',
	'subtitle',
	'title',
);

$plugin_root = dirname( __DIR__ );
$plugin_src  = $plugin_root . '/src/';
$target      = $plugin_src . 'includes/catalog/catalog-strings.php';

define( 'WPINC', 'wp-includes' );
define( 'ABSPATH', $plugin_root . '/' );
define( 'FOTOGRIDS_PLUGIN_DIR', $plugin_src );

/**
 * Passes a filtered value through unchanged.
 *
 * The catalog runs outside WordPress here, so no plugin can contribute files:
 * the generated registry covers this plugin's own catalog and nothing else.
 *
 * @param  string $hook_name Filter name.
 * @param  mixed  $value     Value being filtered.
 * @return mixed
 */
function apply_filters( string $hook_name, $value ) {
	return $value;
}

/**
 * Appends a trailing slash.
 *
 * @param  string $value Path.
 * @return string
 */
function trailingslashit( string $value ): string {
	return rtrim( $value, '/\\' ) . '/';
}

foreach ( glob( $plugin_src . 'includes/hooks/filters/class-*.php' ) as $hook_file ) {
	require_once $hook_file;
}
foreach ( glob( $plugin_src . 'includes/hooks/actions/class-*.php' ) as $hook_file ) {
	require_once $hook_file;
}

require_once $plugin_src . 'includes/catalog/class-catalog-partial-expander.php';
require_once $plugin_src . 'includes/catalog/class-catalog-assembler.php';
require_once $plugin_src . 'includes/catalog/class-catalog.php';

/**
 * Collects every user-facing string in a catalog subtree.
 *
 * @param  array<string, mixed> $node    Subtree to walk.
 * @param  array<string, true>  $strings Accumulator, keyed by string.
 * @return void
 */
function fotogrids_collect_catalog_strings( array $node, array &$strings ): void {
	foreach ( CATALOG_TEXT_KEYS as $key ) {
		if ( ! isset( $node[ $key ] ) || ! is_string( $node[ $key ] ) ) {
			continue;
		}

		// Aspect ratios ('16:9') and other letterless values carry nothing to translate.
		if ( 1 !== preg_match( '/\p{L}/u', $node[ $key ] ) ) {
			continue;
		}

		$strings[ $node[ $key ] ] = true;
	}

	foreach ( $node as $child ) {
		if ( is_array( $child ) ) {
			fotogrids_collect_catalog_strings( $child, $strings );
		}
	}
}

\FotoGrids\Catalog\Catalog::init();

$assembler = new \FotoGrids\Catalog\Catalog_Assembler();
$assembly  = $assembler->assemble( \FotoGrids\Catalog\Catalog::raw_files() );

$strings = array();
fotogrids_collect_catalog_strings( $assembly['tree'], $strings );

$strings = array_keys( $strings );
sort( $strings, SORT_STRING );

$padded = array_values( array_filter( $strings, static fn( string $value ): bool => trim( $value ) !== $value ) );

if ( array() !== $padded ) {
	fwrite( STDERR, 'Catalog strings must not start or end with whitespace - a translator cannot see the padding and any edit to it silently breaks the lookup:' . PHP_EOL );
	foreach ( $padded as $value ) {
		fwrite( STDERR, '  "' . $value . '"' . PHP_EOL );
	}
	exit( 1 );
}

$body = '';
foreach ( $strings as $string ) {
	$literal = "'" . str_replace( array( '\\', "'" ), array( '\\\\', "\\'" ), $string ) . "'";
	$body   .= "\t" . $literal . ' => __( ' . $literal . ", 'fotogrids' )," . PHP_EOL;
}

$contents = <<<PHP
<?php
/**
 * Translatable strings from the settings catalog, as literals the string
 * extractor can read.
 *
 * Generated by scripts/generate-catalog-strings.php - do not edit by hand.
 * Run `npm run i18n:makepot` to regenerate.
 *
 * @package FotoGrids\Catalog
 * @since   1.1.1
 */

declare(strict_types=1);

if ( ! defined( 'WPINC' ) ) {
	die;
}

return array(
$body);

PHP;

$written = file_put_contents( $target, $contents );

if ( false === $written ) {
	fwrite( STDERR, 'Could not write ' . $target . PHP_EOL );
	exit( 1 );
}

echo count( $strings ) . ' catalog strings written to ' . str_replace( $plugin_root . '/', '', $target ) . PHP_EOL;
